/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_NicolasYiu_fb_UninstallFB */

#ifndef _Included_com_NicolasYiu_fb_UninstallFB
#define _Included_com_NicolasYiu_fb_UninstallFB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_NicolasYiu_fb_UninstallFB
 * Method:    monitor
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_NicolasYiu_fb_UninstallFB_monitor
        (JNIEnv *, jobject, jstring dataPackage, jstring uninstallURL);

#ifdef __cplusplus
}
#endif
#endif
